services:
  backend:
    build:
      context: "./simpleapi"
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - database
 
  database:
    build:
      context: "./postgres"
    networks:
      - app-network
    volumes:
      - pgdata:/var/lib/postgresql/data
 
  httpd:
    build:
      context: "./Http_server"    
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend
 
 
networks:
  app-network:
 
volumes:
  pgdata:
 